import  {Todo} from "./todo";
let authors: string[] = ["Alice", "Bob", "Charlie", "David", "Eva", "Frank", "Grace", "Hank", "Ivy", "Jack"];

export const TODOS: Todo [] = [
    
    {
        id: 1,
        title: "Todo 1",
        content: "Content todo 1",
        author: "John Doe",
        isCompleted: true,
        createdAt: new Date(),
        completedAt: null,
    },
    {
        id: 2,
        title: "Todo 2",
        content: "Content todo 2",
        author: "Bob",
        isCompleted: true,
        createdAt: new Date(),
        completedAt: null,
    },
    {
        id: 3,
        title: "Todo 3",
        content: "Content todo 3",
        author: "Charlie",
        isCompleted: true,
        createdAt: new Date(),
        completedAt: null,
    },
    {
        id: 4,
        title: "Todo 4",
        content: "Content todo 4",
        author: "David",
        isCompleted: true,
        createdAt: new Date(),
        completedAt: null,
    },
    {
        id: 5,
        title: "Todo 5",
        content: "Content todo 5",
        author: "Eva",
        isCompleted: true,
        createdAt: new Date(),
        completedAt: null,
    },
    {
        id: 6,
        title: "Todo 6",
        content: "Content todo 6",
        author: "Frank",
        isCompleted: true,
        createdAt: new Date(),
        completedAt: null,
    },
    {
        id: 7,
        title: "Todo 7",
        content: "Content todo 7",
        author: "Grace",
        isCompleted: true,
        createdAt: new Date(),
        completedAt: null,
    },
    {
        id: 8,
        title: "Todo 8",
        content: "Content todo 8",
        author: "Hank",
        isCompleted: true,
        createdAt: new Date(),
        completedAt: null,
    },
    {
        id: 9,
        title: "Todo 9",
        content: "Content todo 9",
        author: "Ivy",
        isCompleted: true,
        createdAt: new Date(),
        completedAt: null,
    },
    {
        id: 10,
        title: "Todo 10",
        content: "Content todo 10",
        author: "Jack",
        isCompleted: true,
        createdAt: new Date(),
        completedAt: null,
    },
]